- name: Install NGINX
  hosts: all
  become: yes
  tasks:
    - name: Add EPEL repository for RHEL/CentOS
      yum:
        name: epel-release
        state: present
      when: ansible_distribution in ["CentOS", "RedHat"] and ansible_distribution_major_version | int < 9

    - name: Enable EPEL for Amazon Linux
      command: amazon-linux-extras enable epel
      when: ansible_distribution == "Amazon"

    - name: Update package cache
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install Nginx
      yum:
        name: nginx
        state: present
